# src/utils/templates/business.py

def get_commercial_finance_templates():
    """強化商用金融與支付場景 (維持現有豐富度)"""
    return [
        ["支付通知：已轉帳 HKD ", "{money}", " 至帳戶 ", "{account}", " (", "{name}", ")。"],
        ["入數紙證明：收款人 ", "{name}", "，銀行代碼 ", "{org}", "，帳號 ", "{account}", "。"],
        ["FPS 識別碼：", "{phone}", " 或 ", "{account}", " (受款人: ", "{name}", ")。"],
        ["Cheque payable to: ", "{name}", " (A/C No: ", "{account}", ")."],
        ["Wire Transfer Info: Beneficiary ", "{name}", ", IBAN: ", "{account}", "."],
        ["TT Payment to ", "{org}", " A/C ", "{account}", " for invoice ", "{id_num}", "."],
        ["MPF 強積金供款確認：僱員 ", "{name}", "，帳號 ", "{account}", "。"],
        ["帳號 ", "{account}", " 請核對。"],
        ["Bank A/C: ", "{account}", " (Saving)"],
        ["轉數快識別碼：", "{id_num}", " / ", "{phone}", "。"],
        ["REF NO: ", "{account}", " (Urgent)"],
        ["身份證號碼 ", "{id_num}", " 已登記。"],
        ["ID: ", "{id_num}", "."],
        ["顧客 ", "{name}", " (VIP ", "{account}", ")。"],
        ["請安排匯款至 ", "{bank}", " 帳號 ", "{account}", "，抬頭 ", "{org}", "。"],
        ["已收到來自 ", "{name}", " 的支票，號碼 ", "{account}", "。"],
        ["月結單顯示 ", "{account}", " 有一筆不明款項。"],
        ["自動轉帳失敗，請更新 ", "{bank}", " 戶口 ", "{account}", " 資料。"],
        ["信用卡還款：", "{account}", "，金額 $", "{money}", "。"],
        ["保費扣款授權書：A/C ", "{account}", " (持有人: ", "{name}", ")。"],
        ["Please remit payment to Account Number: ", "{account}", " at ", "{bank}", "."],
        ["Invoice #99281, payment via FPS ID ", "{phone}", "."],
        ["薪資單：基本薪金存入 ", "{account}", "。"],
        ["供應商 ", "{org}", " 要求更改收款帳號為 ", "{account}", "。"],
        ["定期存款證明：", "{account}", "，本金 ", "{money}", " 元。"],
        ["股票戶口 ", "{account}", " 買入匯豐控股。"],
        ["分紅派息將存入登記戶口 ", "{account}", "。"],
        ["退款通知：款項已退回至原付款帳戶 ", "{account}", "。"],
        ["慈善捐款帳號：", "{org}", " - ", "{bank}", " ", "{account}", "。"],
        ["物業管理費由戶口 ", "{account}", " 自動扣除。"],
        ["租金收入證明：租客 ", "{name}", " 轉帳至 ", "{account}", "。"],
        ["Payment Confirmation: Transferred to ", "{account}", " successfully."],
        ["Vendor Bank Details: ", "{bank}", ", Swift Code: HSBCHKHH, A/C: ", "{account}", "."],
        ["FPS ID ", "{email}", " is associated with ", "{name}", "."],
        ["PayMe link sent to ", "{phone}", " for payment."],
        ["請保留入數紙，轉帳至 ", "{account}", " 後 WhatsApp 通知。"],
        ["公司帳戶 ", "{account}", " 結餘不足。"],
        ["授權 ", "{org}", " 從本人帳戶 ", "{account}", " 扣除服務費。"],
        ["Direct Debit Set up for Account: ", "{account}", "."],
        ["按揭還款帳戶：", "{account}", "，下期供款日 15 號。"],
        ["投資戶口 ", "{account}", " 已開通美股交易權限。"],
        ["請勿轉帳至舊帳號 ", "{account}", "，該戶口已取消。"],
        ["Verified by Visa: Card ending in ", "{account}", "."],
        ["AlipayHK 轉帳：", "{phone}", " (", "{name}", ")。"],
        ["WeChat Pay 收款碼對應帳號：", "{account}", "。"],
        ["客戶 ", "{name}", " 查詢匯款進度，Ref: ", "{account}", "。"],
        ["Settlement Account: ", "{account}", " (HKD Only)."],
        ["請確認收款人帳號 ", "{account}", " 是否正確。"],
        ["網上銀行轉帳限額設定：帳戶 ", "{account}", "。"],
        ["緊急提款：由 ", "{account}", " 提取現金 $", "{money}", "。"]
    ]

def get_customer_service_and_hr_templates():
    """強化客戶服務與人力資源場景 (維持現有豐富度)"""
    return [
        ["CV 篩選：申請人 ", "{name}", "，聯絡電話 ", "{phone}", "，現居 ", "{addr}", "。"],
        ["入職通知：請 ", "{name}", " (ID: ", "{id_num}", ") 於下週報到。"],
        ["客戶投訴記錄：客戶姓名 ", "{name}", "，聯絡方式 ", "{phone}", "。"],
        ["Internal Memo: Author ", "{name}", " (Staff ID: ", "{id_num}", ")."],
        ["面試安排：", "{name}", " 小姐，時間：週三下午。"],
        ["請聯絡 HR 部門 ", "{name}", " 領取職員證。"],
        ["員工 ", "{name}", " (工號 ", "{code}", ") 已提交請假申請。"],
        ["Reference Check: Candidate ", "{name}", ", previous employer ", "{org}", "."],
        ["緊急聯絡人資料更新：", "{name}", "，關係：父子，電話：", "{phone}", "。"],
        ["客戶服務熱線：", "{phone}", "，服務時間朝九晚六。"],
        ["投訴人 ", "{name}", " 聲稱未收到貨品，訂單號 ", "{order_id}", "。"],
        ["請將履歷表電郵至 ", "{email}", "，註明申請職位。"],
        ["離職證明書：茲證明 ", "{name}", " 曾於本公司任職。"],
        ["醫療卡號碼：", "{account}", "，持有人：", "{name}", "。"],
        ["員工福利：", "{org}", " 提供團體醫療保險。"],
        ["Training Session Attendance: ", "{name}", ", ", "{name}", ", ", "{name}", "."],
        ["如有查詢，請致電 ", "{phone}", " 與客戶服務主任 ", "{name}", " 聯絡。"],
        ["會員登記：", "{name}", "，出生日期：1990年，地址：", "{addr}", "。"],
        ["VIP 客戶 ", "{name}", " 要求升級服務。"],
        ["員工通告：", "{name}", " 晉升為高級經理。"],
        ["新入職同事 ", "{name}", " 將加入市場部。"],
        ["請 ", "{name}", " 到人事部簽署合約 (ID: ", "{id_num}", ")。"],
        ["客戶回饋：", "{name}", " 表示對服務非常滿意。"],
        ["退貨申請：客戶 ", "{name}", "，電話 ", "{phone}", "。"],
        ["Candidate ", "{name}", " lives in ", "{addr}", ", willing to relocate."],
        ["Staff ", "{name}", " lost access card ", "{code}", "."],
        ["請更新員工 ", "{name}", " 的住址證明：", "{addr}", "。"],
        ["保險索償申請人：", "{name}", "，保單號碼 ", "{account}", "。"],
        ["客戶服務中心地址：", "{addr}", "。"],
        ["招聘日：請帶備身份證 ", "{id_num}", " 及學歷證明。"],
        ["員工 ", "{name}", " 將於本月底退休。"],
        ["Please verify the identity of customer ", "{name}", " (ID: ", "{id_num}", ")."],
        ["Receptionist: ", "{name}", ", please forward calls to ", "{phone}", "."],
        ["客戶 ", "{name}", " 投訴 ", "{org}", " 服務態度欠佳。"],
        ["員工考勤記錄：", "{name}", " 遲到 15 分鐘。"],
        ["薪酬調整通知信已發給 ", "{name}", "。"],
        ["請 ", "{name}", " 盡快補交強積金成員登記表。"],
        ["客戶 ", "{name}", " 更改聯絡電話為 ", "{phone}", "。"],
        ["HR Hotline: ", "{phone}", " or email ", "{email}", "."],
        ["Interview feedback for ", "{name}", ": Excellent communication skills."],
        ["員工 ", "{name}", " 申請在家工作。"],
        ["請將文件交給 ", "{org}", " 的 ", "{name}", " 先生。"],
        ["客戶服務部：", "{name}", " 接聽了您的來電。"],
        ["投訴編號 ", "{code}", "，跟進人：", "{name}", "。"],
        ["員工手冊已發送至 ", "{email}", "。"],
        ["兼職合約：", "{name}", "，時薪 $60。"],
        ["實習生 ", "{name}", " 表現優異，建議轉正。"],
        ["請 ", "{name}", " (ID ", "{id_num}", ") 到 3 號櫃檯辦理手續。"]
    ]

def get_hong_kong_business_templates():
    """針對香港商用環境的數據增強 (維持現有豐富度)"""
    return [
        ["現收到由 ", "{org}", " 發出嘅最新工程招標公告。"],
        ["", "{org}", " 宣佈將於下月推行全港性嘅節能計劃。"],
        ["公司地址位於 ", "{addr}", "，近港鐵站出口。"],
        ["請將發票寄去 ", "{addr}", "，收件人係 ", "{name}", "。"],
        ["Office Location: ", "{addr}", " (Attention to HR Department)."],
        ["我係 ", "{org}", " 嘅高級經理 ", "{name}", "，想同你 Confirm 返個期。"],
        ["請聯絡行政總裁 ", "{name}", " 先生以獲取更多資訊。"],
        ["Project Manager ", "{name}", " will be in charge of this task."],
        ["根據本合約，", "{name}", " (以下簡稱「甲方」) 需向 ", "{org}", " 支付費用。"],
        ["授權代表：", "{name}", "，職位：", "{org}", " 總監。"],
        ["", "{org}", " 位於 ", "{addr}", " 嘅分店將於下週開幕。"],
        ["如有查詢，請與 ", "{org}", " 市場部聯絡。"],
        ["本公司 ", "{org}", " 保留最終決定權。"],
        ["送貨地址係 ", "{addr}", "，請在到達前致電 ", "{phone}", "。"],
        ["", "{name}", " 代表 ", "{org}", " 簽署此文件。"],
        ["Registered Office: ", "{addr}", ", Hong Kong."],
        ["", "{org}", " 是一間在香港註冊的有限公司。"],
        ["請寄支票到 ", "{addr}", "，抬頭寫 ", "{org}", "。"],
        ["", "{name}", " (Director of ", "{org}", ") attended the meeting."],
        ["物業地址：", "{addr}", "，業主：", "{name}", "。"],
        ["", "{org}", " 總部設於 ", "{addr}", "。"],
        ["請將報價單 Fax 去 ", "{phone}", " 或 Email 給 ", "{email}", "。"],
        ["", "{org}", " 獲頒發優質服務獎。"],
        ["", "{name}", " 先生係 ", "{org}", " 嘅創辦人。"],
        ["郵寄地址：", "{addr}", " (信封請註明「機密」)。"],
        ["", "{org}", " 提供的服務受條款約束。"],
        ["供應商 ", "{org}", " 地址更改為 ", "{addr}", "。"],
        ["", "{name}", " 獲委任為 ", "{org}", " 的非執行董事。"],
        ["Warehouse Address: ", "{addr}", "."],
        ["", "{org}", " 贊助了是次活動。"],
        ["請於辦公時間內親臨 ", "{addr}", " 辦理。"],
        ["", "{org}", " 客戶服務中心位於 ", "{addr}", "。"],
        ["", "{name}", ", CEO of ", "{org}", ", announced the results."],
        ["法律顧問：", "{org}", "，地址：", "{addr}", "。"],
        ["承建商：", "{org}", "，負責人：", "{name}", "。"],
        ["", "{org}", " 嘅股票代號係 ", "{code}", "。"],
        ["請交回表格至 ", "{org}", " 收集箱。"],
        ["", "{name}", " 持有 ", "{org}", " 51% 股份。"],
        ["核數師：", "{org}", " 會計師事務所。"],
        ["", "{org}", " 澄清有關 ", "{name}", " 的失實報導。"],
        ["Branch Manager: ", "{name}", ", ", "{org}", "."],
        ["", "{org}", " 致力於可持續發展。"],
        ["請將回條寄回 ", "{addr}", " ", "{org}", " 收。"],
        ["", "{name}", " 辭任 ", "{org}", " 財務總監一職。"],
        ["", "{org}", " 位於 ", "{addr}", " 的辦事處暫停服務。"],
        ["代理人：", "{name}", "，所屬公司：", "{org}", "。"],
        ["", "{org}", " 成功投得 ", "{addr}", " 地皮。"],
        ["秘書公司：", "{org}", "。"]
    ]
    
def get_long_entity_templates():
    """(維持現有豐富度)"""
    return [
        ["據 ", "{org}", " 今日披露，該項目已完工。"],
        ["", "{org}", " 分行地址位於 ", "{addr}", "。"],
        ["受款人為 ", "{org}", "，請於三日內過數。"],
        ["", "{org}", " 係全港最大嘅公共運輸機構之一。"],
        ["由 ", "{org}", " 簽發的證明文件。"],
        ["根據 ", "{org}", " 發布的最新指引。"],
        ["", "{org}", " 聯合 ", "{org}", " 舉辦了這次研討會。"],
        ["位於 ", "{addr}", " 的 ", "{org}", " 總部大樓。"],
        ["", "{org}", " 以及 ", "{org}", " 簽署了合作備忘錄。"],
        ["消息指，", "{org}", " 計劃裁員。"],
        ["", "{org}", " 的發言人 ", "{name}", " 拒絕置評。"],
        ["這項研究由 ", "{org}", " 資助。"],
        ["", "{org}", " 旗下的子公司 ", "{org}", "。"],
        ["市民可前往 ", "{org}", " 各分行查詢。"],
        ["", "{org}", " 位於 ", "{addr}", " 的旗艦店。"],
        ["投訴對象：", "{org}", "，事由：濫收費用。"],
        ["", "{org}", " 正式收購 ", "{org}", "。"],
        ["由 ", "{org}", " 主辦，", "{org}", " 協辦。"],
        ["", "{org}", " 的股價今日大跌。"],
        ["", "{org}", " 位於 ", "{addr}", " 的舊址將進行重建。"],
        ["據 ", "{org}", " 統計，今年經濟增長放緩。"],
        ["", "{org}", " 宣布派發特別股息。"],
        ["", "{org}", " 捲入 ", "{name}", " 的貪污案。"],
        ["請參閱 ", "{org}", " 的年報。"],
        ["", "{org}", " 獲得了 ", "{org}", " 的獨家代理權。"],
        ["", "{org}", " 位於 ", "{addr}", " 的中心發生火警。"],
        ["", "{org}", " 呼籲市民提高警覺。"],
        ["", "{org}", " 承諾會改善服務質素。"],
        ["", "{org}", " 被 ", "{org}", " 評為最佳僱主。"],
        ["", "{org}", " 位於 ", "{addr}", " 的實驗室。"],
        ["", "{org}", " 推出全新產品系列。"],
        ["", "{org}", " 與 ", "{org}", " 達成和解協議。"],
        ["", "{org}", " 的創辦人 ", "{name}", " 逝世。"],
        ["", "{org}", " 位於 ", "{addr}", " 的地盤發生意外。"],
        ["", "{org}", " 獲批 ", "{addr}", " 的發展權。"],
        ["", "{org}", " 向 ", "{org}", " 捐贈了物資。"],
        ["", "{org}", " 位於 ", "{addr}", " 的商場人流稀少。"],
        ["", "{org}", " 澄清無意撤出香港。"],
        ["", "{org}", " 聘請 ", "{org}", " 進行審計。"],
        ["", "{org}", " 位於 ", "{addr}", " 的貨倉。"],
        ["", "{org}", " 歡迎 ", "{org}", " 加入聯盟。"],
        ["", "{org}", " 的前身是 ", "{org}", "。"],
        ["", "{org}", " 位於 ", "{addr}", " 的展廳。"],
        ["", "{org}", " 將於 ", "{addr}", " 舉行招聘會。"],
        ["", "{org}", " 控告 ", "{name}", " 侵權。"],
        ["", "{org}", " 位於 ", "{addr}", " 的停車場。"],
        ["", "{org}", " 榮獲 ", "{org}", " 頒發環保獎。"],
        ["", "{org}", " 宣布停牌。"]
    ]

def get_org_position_separation_templates():
    """(維持現有豐富度)"""
    return [
        ["我是 ", "{org}", " 的 ", "經理", " ", "{name}", "。"],
        ["", "{org}", " ", "行政總裁", " ", "{name}", " 昨日表示公司業績良好。"],
        ["請聯絡 ", "{org}", " ", "人力資源部主管", " ", "{name}", " 先生。"],
        ["", "{name}", " 現擔任 ", "{org}", " 的 ", "首席財務官", "。"],
        ["出席者包括 ", "{org}", " ", "主席", " ", "{name}", " 及副主席。"],
        ["前 ", "{org}", " ", "主席", " ", "{name}", " 出席會議。"],
        ["", "{name}", "，", "{org}", " 創辦人，曾任職於 ", "{org}", "。"],
        ["", "{org}", " ", "董事總經理", " ", "{name}", " 接受訪問。"],
        ["", "{name}", " 獲委任為 ", "{org}", " ", "執行董事", "。"],
        ["據 ", "{org}", " ", "發言人", " ", "{name}", " 透露。"],
        ["", "{name}", " 辭去 ", "{org}", " ", "顧問", " 一職。"],
        ["", "{org}", " ", "首席執行官", " ", "{name}", " 發表講話。"],
        ["", "{name}", " 被提名為 ", "{org}", " ", "獨立非執行董事", "。"],
        ["", "{org}", " ", "總工程師", " ", "{name}", " 負責此項目。"],
        ["", "{name}", " 轉投 ", "{org}", " 出任 ", "副總裁", "。"],
        ["", "{org}", " ", "合夥人", " ", "{name}", " 分析市場走勢。"],
        ["", "{name}", " 升任 ", "{org}", " ", "營運總監", "。"],
        ["", "{org}", " ", "主席", " ", "{name}", " 主持股東大會。"],
        ["", "{name}", " 是 ", "{org}", " 的 ", "資深研究員", "。"],
        ["", "{org}", " ", "法律顧問", " ", "{name}", " 發出律師信。"],
        ["", "{name}", " 加盟 ", "{org}", " 擔任 ", "創意總監", "。"],
        ["", "{org}", " ", "秘書", " ", "{name}", " 正在整理文件。"],
        ["", "{name}", " 曾任 ", "{org}", " ", "部門主管", "。"],
        ["", "{org}", " ", "財務總監", " ", "{name}", " 預警盈利倒退。"],
        ["", "{name}", " 兼任 ", "{org}", " ", "榮譽主席", "。"],
        ["", "{org}", " ", "分析師", " ", "{name}", " 建議買入。"],
        ["", "{name}", " 獲 ", "{org}", " 聘為 ", "技術顧問", "。"],
        ["", "{org}", " ", "總裁", " ", "{name}", " 宣布退休。"],
        ["", "{name}", " 代表 ", "{org}", " ", "職工會", " 發言。"],
        ["", "{org}", " ", "會計師", " ", "{name}", " 簽署審計報告。"],
        ["", "{name}", " 是 ", "{org}", " 的 ", "大股東", "。"],
        ["", "{org}", " ", "經理", " ", "{name}", " 處理客戶投訴。"],
        ["", "{name}", " 擔任 ", "{org}", " ", "項目經理", "。"],
        ["", "{org}", " ", "設計師", " ", "{name}", " 展示新作品。"],
        ["", "{name}", " 獲選為 ", "{org}", " ", "年度最佳員工", "。"],
        ["", "{org}", " ", "主編", " ", "{name}", " 撰寫社論。"],
        ["", "{name}", " 是 ", "{org}", " 的 ", "實習生", "。"],
        ["", "{org}", " ", "行政助理", " ", "{name}", " 安排會議。"],
        ["", "{name}", " 晉升為 ", "{org}", " ", "區域經理", "。"],
        ["", "{org}", " ", "保安主任", " ", "{name}", " 巡視大樓。"],
        ["", "{name}", " 是 ", "{org}", " 的 ", "註冊護士", "。"],
        ["", "{org}", " ", "校長", " ", "{name}", " 在畢業禮致詞。"],
        ["", "{name}", " 當選 ", "{org}", " ", "會長", "。"],
        ["", "{org}", " ", "司庫", " ", "{name}", " 匯報財政狀況。"],
        ["", "{name}", " 是 ", "{org}", " 的 ", "創始成員", "。"],
        ["", "{org}", " ", "總監", " ", "{name}", " 出席剪綵儀式。"]
    ]

def get_job_title_boundary_templates():
    """(維持現有豐富度)"""
    titles = ["主席", "副主席", "總裁", "CEO", "經理", "總監", "主任", "顧問", "外賣員", "司機", 
              "工程師", "會計師", "律師", "分析師", "研究員", "助理", "秘書", "文員", "保安", "清潔工"]
    templates = []
    
    for t in titles:
        # 1. 緊密連接模式 (Hard Case: 長和主席)
        templates.append(["曾任職於", "{org}", t])
        templates.append(["現任", "{org}", t])
        templates.append(["", "{org}", t, "表示"])
        templates.append(["我是", "{org}", t])
        
        # 2. 姓名夾擊模式
        templates.append(["", "{org}", t, "{name}", ""]) 
        templates.append(["", "{org}", "的", t, "是", "{name}", ""])
        
        # 3. 履歷/介紹模式
        templates.append(["工作經驗：", "{org}", t])
        templates.append(["Title: ", "{org}", " ", t]) 
        templates.append(["職位：", "{org}", t])
        templates.append(["", "{name}", " (", "{org}", t, ")"])
        templates.append(["介紹返，呢位係 ", "{org}", t, " ", "{name}", "。"])
        templates.append(["", "{org}", t, "職位空缺。"])
        templates.append(["", "{name}", " 升職做 ", "{org}", t, "。"])
        
    more_templates = [
        ["", "{org}", "行政總裁", "{name}", "出席了會議。"],
        ["前", "{org}", "財務總監", "{name}", "被捕。"],
        ["", "{org}", "營運經理", "一職現正招聘。"],
        ["", "{name}", "獲委任為", "{org}", "執行董事", "。"],
        ["據", "{org}", "發言人", "稱。"],
        ["", "{name}", "轉投", "{org}", "擔任", "副總裁", "。"],
        ["", "{org}", "創辦人", "{name}", "身家暴漲。"],
        ["", "{org}", "主席", "發表新年賀詞。"],
        ["", "{name}", "係", "{org}", "資深顧問", "。"],
        ["", "{org}", "總工程師", "負責監督。"],
        ["", "{org}", "合夥人", "{name}", "分析。"],
        ["", "{name}", "任職", "{org}", "分析員", "多年。"],
        ["", "{org}", "保安", "拒絕記者進入。"],
        ["", "{org}", "司機", "{name}", "發生意外。"],
        ["", "{org}", "清潔工", "發現可疑物品。"],
        ["", "{org}", "實習生", "{name}", "表現良好。"],
        ["", "{org}", "會計", "涉嫌虧空公款。"],
        ["", "{name}", "被", "{org}", "解僱，職位是", "經理", "。"],
        ["", "{org}", "董事會主席", "{name}", "辭職。"],
        ["", "{org}", "區域總監", "{name}", "視察業務。"]
    ]
    
    return templates + more_templates

def get_id_confusion_templates():
    """(維持現有豐富度)"""
    return [
        ["身份證號為 ", "{id_num}", "。"],
        ["登記證件：", "{id_num}", " (必須核對)。"],
        ["客人證件號碼是 ", "{id_num}", "，請記錄。"],
        ["", "{name}", " 的身份證號碼係 ", "{id_num}", "。"],
        ["HKID: ", "{id_num}", "."],
        ["Identity Card No: ", "{id_num}", "."],
        ["電話 ", "{phone}", "，身份證 ", "{id_num}", "。"],
        ["ID: ", "{id_num}", ", Mobile: ", "{phone}", "."],
        ["聯絡方法：", "{phone}", " / 證件：", "{id_num}", "。"],
        ["請提供身份證號碼 (e.g. ", "{id_num}", ")。"],
        ["", "{id_num}", " 係我個 ID。"],
        ["身分證：", "{id_num}", "。"],
        ["請填寫 HKID: ", "{id_num}", "。"],
        ["核對身份：", "{name}", ", ", "{id_num}", "。"],
        ["", "{id_num}", " (ID)"],
        ["ID Card: ", "{id_num}", " (Copy)."],
        ["持有身分證號碼 ", "{id_num}", " 的人士。"],
        ["", "{name}", " (", "{id_num}", ")"],
        ["證件號：", "{id_num}", " / 電話：", "{phone}", "。"],
        ["Mobile: ", "{phone}", " / ID: ", "{id_num}", "."],
        ["請致電 ", "{phone}", " 或傳真身份證副本 ", "{id_num}", "。"],
        ["", "{id_num}", " 不是電話號碼，是身份證。"],
        ["我的電話係 ", "{phone}", "，ID 係 ", "{id_num}", "。"],
        ["", "{phone}", " (Phone), ", "{id_num}", " (ID)."],
        ["登記人資料：姓名 ", "{name}", "，ID ", "{id_num}", "，Tel ", "{phone}", "。"],
        ["遺失身份證：", "{id_num}", "。"],
        ["", "{id_num}", " is the HKID number."],
        ["Please verifying ID ", "{id_num}", "."],
        ["客戶 ", "{name}", " (", "{id_num}", ") 申請更改地址。"],
        ["身分證號碼 ", "{id_num}", " 已失效。"],
        ["", "{id_num}", " (香港永久性居民身份證)。"],
        ["", "{id_num}", " (R)"],
        ["Sample ID: ", "{id_num}", "."],
        ["輸入證件號碼：", "{id_num}", "。"],
        ["", "{id_num}", " 係正確嘅號碼。"],
        ["身份證 ", "{id_num}", " 登記。"],
        ["", "{name}", " [", "{id_num}", "]"],
        ["Personal ID: ", "{id_num}", "."],
        ["Identification: ", "{id_num}", "."],
        ["", "{id_num}", " / ", "{phone}", " (ID/Phone)"],
        ["Tel: ", "{phone}", ", HKID: ", "{id_num}", "."],
        ["", "{id_num}", " (括號內數字為校驗碼)。"],
        ["證件類別：香港身份證，號碼：", "{id_num}", "。"],
        ["", "{id_num}", " (Smart ID)."],
        ["請出示身份證 ", "{id_num}", " 以便核實。"],
        ["", "{name}", ", ID number ", "{id_num}", ", contacted us."],
        ["", "{id_num}", " - Do not disclose."]
    ]

def get_weak_entity_templates():
    """
    🔥 [關鍵更新] 極大化擴充弱點實體的語境多樣性 (擴充至 150+ 條)
    目標：透過不同場景，讓模型真正理解 Context，無需依賴暴力複製。
    """
    return [
        # ==========================================
        # 🚗 LICENSE_PLATE (車牌) - 停車、違規、買賣、行車記錄、租賃...
        # ==========================================
        ["車牌號碼 ", "{plate}", " 登記車主係 ", "{name}", "。"],
        ["駕駛車輛：", "{plate}", " (", "{org}", " 公司車)"],
        ["目擊涉事車輛 ", "{plate}", " 駛離現場。"],
        ["License Plate: ", "{plate}", "."],
        ["登記號碼：", "{plate}", "，車型：私家車。"],
        ["車牌 ", "{plate}", " 已過期，請盡快續牌。"],
        ["Vehicle Reg Mark: ", "{plate}", "."],
        ["停車場月租車輛：", "{plate}", " (車主: ", "{name}", ")"],
        ["請 ", "{plate}", " 車主盡快移車，你阻住路口。"],
        ["違例泊車定額罰款通知書：車輛 ", "{plate}", "。"],
        ["Car Park Level 3, Spot 45: ", "{plate}", " reserved."],
        ["二手車買賣合約：標的車輛 ", "{plate}", "，成交價 $", "{money}", "。"],
        ["的士 ", "{plate}", " 司機態度惡劣，我要投訴。"],
        ["Uber 司機 ", "{name}", " (車牌: ", "{plate}", ") 已到達。"],
        ["", "{plate}", " 係架紅色跑車。"],
        ["警方通緝車輛：", "{plate}", "。"],
        ["", "{plate}", " 入左停車場。"],
        ["請問車牌 ", "{plate}", " 係咪你架車？"],
        ["租車確認：", "{org}", " 已預留車輛 ", "{plate}", "。"],
        ["", "{plate}", " 需要維修。"],
        ["車主 ", "{name}", " (車牌 ", "{plate}", ") 請聯絡管理處。"],
        ["Registration No.: ", "{plate}", "."],
        ["", "{plate}", " (Private Car)."],
        ["", "{plate}", " 停泊在雙黃線。"],
        ["", "{plate}", " 發生交通意外。"],
        ["行車證已過期：", "{plate}", "。"],
        ["", "{plate}", " 申請封閉道路通行許可證。"],
        ["校巴 ", "{plate}", " 準時到達。"],
        ["貨車 ", "{plate}", " 正在卸貨。"],
        ["請安排 ", "{plate}", " 進行年檢。"],
        ["My car plate is ", "{plate}", "."],
        ["Look at that car, ", "{plate}", ", driving so fast!"],
        ["", "{plate}", " 被抄牌。"],
        ["車位已租予 ", "{plate}", "。"],
        ["", "{plate}", " 登記使用自動繳費服務。"],
        ["隧道費：車輛 ", "{plate}", "，金額 $20。"],
        ["", "{plate}", " (Tesla Model Y)"],
        ["", "{plate}", " (Toyota Alphard)"],
        ["Lost Key: Vehicle ", "{plate}", "."],
        ["Valet Parking Ticket: ", "{plate}", "."],
        ["Please move your car ", "{plate}", " immediately."],
        ["", "{plate}", " is blocking the fire exit."],
        ["Tow truck dispatched for ", "{plate}", "."],
        ["Assigning driver ", "{name}", " to vehicle ", "{plate}", "."],
        ["", "{plate}", " 報失。"],
        ["發現棄置車輛：", "{plate}", "。"],
        ["", "{plate}", " 通過廢氣測試。"],
        ["申請保留車牌號碼：", "{plate}", "。"],
        ["自訂車牌：", "{plate}", "。"],
        ["拍賣車牌：", "{plate}", "，底價 $5000。"],

        # ==========================================
        # 💰 ACCOUNT (銀行戶口) - 薪資、網購、貸款、水電費、投資...
        # ==========================================
        ["請將款項存入 ", "{bank}", " 戶口號碼 ", "{account}", "。"],
        ["銀行轉帳記錄：", "{account}", " (", "{name}", ")"],
        ["FPS ID: ", "{account}", " (非電話號碼)"], 
        ["Account No: ", "{account}", "."],
        ["入數紙：", "{account}", "，金額 $", "{money}", "。"],
        ["收款帳號：", "{account}", "，請核對。"],
        ["公司薪資轉帳：", "{org}", " -> 僱員戶口 ", "{account}", "。"],
        ["自動轉帳授權書：扣款戶口 ", "{account}", " (", "{bank}", ")。"],
        ["網店付款：PayMe / FPS 到 ", "{account}", "，記得 Cap 圖。"],
        ["貸款還款戶口：", "{account}", "，每月供款 $", "{money}", "。"],
        ["捐款熱線：請存入慈善基金戶口 ", "{account}", "。"],
        ["警惕詐騙：陌生人要求轉帳至 ", "{account}", " 切勿相信。"],
        ["Direct Debit Authorization: A/C ", "{account}", "."],
        ["", "{account}", " 係我個銀行戶口。"],
        ["請過數去 ", "{account}", " (恒生)。"],
        ["Bank Transfer: ", "{account}", "."],
        ["", "{account}", " (Saving Account)."],
        ["Credit Card A/C: ", "{account}", "."],
        ["", "{org}", " Bank Account: ", "{account}", "."],
        ["轉帳 $", "{money}", " 到 ", "{account}", "。"],
        ["我的戶口號碼係 ", "{account}", "。"],
        ["", "{account}", " 收到款項未？"],
        ["請存入 ", "{account}", "。"],
        ["Beneficiary Account: ", "{account}", "."],
        ["", "{account}", " (Current A/C)."],
        ["Joint Account: ", "{account}", " (", "{name}", " & ", "{name}", ")."],
        ["水費單：繳費編號 ", "{account}", "。"],
        ["電費單：帳戶號碼 ", "{account}", "。"],
        ["差餉繳納：帳號 ", "{account}", "。"],
        ["Please credit to account ", "{account}", "."],
        ["Refund processed to ", "{account}", "."],
        ["", "{account}", " 餘額不足。"],
        ["請更新自動轉帳戶口為 ", "{account}", "。"],
        ["投資戶口 ", "{account}", " 結單。"],
        ["強積金供款帳戶：", "{account}", "。"],
        ["", "{account}", " 已凍結。"],
        ["Suspicious activity detected on account ", "{account}", "."],
        ["", "{account}", " (HKD Savings)"],
        ["", "{account}", " (USD Current)"],
        ["Transfer from ", "{account}", " to ", "{account}", "."],
        ["", "{account}", " is the correct number."],
        ["確認收款帳戶：", "{account}", "。"],
        ["請勿轉帳至 ", "{account}", "。"],
        ["", "{account}", " 係公司戶口。"],
        ["", "{account}", " 係私人戶口。"],
        ["支票存款至 ", "{account}", "。"],
        ["", "{account}", " 開戶日期：2020年。"],
        ["取消戶口：", "{account}", "。"],
        ["", "{account}", " (綜合戶口)。"],
        ["定期存款帳戶 ", "{account}", " 到期。"],

        # ==========================================
        # 📞 PHONE (電話) - 快遞、緊急、推銷、預約、驗證碼...
        # ==========================================
        ["有事請致電 ", "{phone}", " 搵陳生。"],
        ["WhatsApp: ", "{phone}", " (拒絕致電)"],
        ["查詢熱線：", "{phone}", "。"],
        ["聯絡電話：", "{phone}", " / ", "{phone}", "。"],
        ["Booking Hotline: ", "{phone}", "."],
        ["SMS 確認碼已發送至 ", "{phone}", "。"],
        ["順豐快遞員：", "{phone}", "，到咗樓下請開門。"],
        ["緊急聯絡人：", "{name}", " (電話: ", "{phone}", ")"],
        ["請勿致電 ", "{phone}", "，此號碼已停用。"],
        ["收到來自 ", "{phone}", " 的可疑來電，聲稱係入境處。"],
        ["維修師傅電話係 ", "{phone}", "，你可以直接約時間。"],
        ["客戶服務 WhatsApp：", "{phone}", " (只限文字訊息)。"],
        ["24-hour Support: ", "{phone}", "."],
        ["Call me at ", "{phone}", "."],
        ["", "{phone}", " 係我電話。"],
        ["請回電 ", "{phone}", "。"],
        ["Fax: ", "{phone}", "."],
        ["Mobile: ", "{phone}", "."],
        ["Tel: ", "{phone}", "."],
        ["", "{phone}", " (Mr. Chan)."],
        ["失物認領請致電 ", "{phone}", "。"],
        ["訂座電話：", "{phone}", "。"],
        ["", "{phone}", " (Office)."],
        ["", "{phone}", " (Home)."],
        ["我個新號碼係 ", "{phone}", "，請更新。"],
        ["Please call ", "{phone}", " for assistance."],
        ["Signal: ", "{phone}", "."],
        ["WeChat: linked to ", "{phone}", "."],
        ["Telegram: ", "{phone}", "."],
        ["Verification code sent to ", "{phone}", "."],
        ["One-Time Password (OTP) sent to ", "{phone}", "."],
        ["Unable to reach ", "{phone}", "."],
        ["", "{phone}", " is busy."],
        ["Leave a message for ", "{phone}", "."],
        ["Dial ", "{phone}", " extension 101."],
        ["Forwarding calls to ", "{phone}", "."],
        ["請致電 ", "{phone}", " 預約睇樓。"],
        ["招聘熱線：", "{phone}", "。"],
        ["報名請電：", "{phone}", "。"],
        ["", "{phone}", " (只限緊急情況)。"],
        ["傳真機號碼：", "{phone}", "。"],
        ["", "{phone}", " 係呃人電話。"],
        ["收到 ", "{phone}", " 嘅短訊。"],
        ["請確認電話號碼 ", "{phone}", " 是否正確。"],
        ["更改電話號碼至 ", "{phone}", "。"],
        ["", "{phone}", " (Main Line)."],
        ["", "{phone}", " (Direct Line)."],
        ["Hotline: ", "{phone}", "."]
    ]